/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tauargus_extern_TauArgusX */

#ifndef _Included_tauargus_extern_TauArgusX
#define _Included_tauargus_extern_TauArgusX
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tauargus_extern_TauArgusX
 * Method:    SetProgressListener
 * Signature: (JLtauargus/extern/IProgressListener;)V
 */
JNIEXPORT void JNICALL Java_tauargus_extern_TauArgusX_SetProgressListener
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
