name: Build TauArgusJava.dll

on:
  #push:
  # branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build TauArgusJava.dll for Windows
    runs-on: windows-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SetUp Java (Zulu 8)
        uses: actions/setup-java@v3      
        with:
          distribution: 'zulu'
          java-version: '8'
          architecture: x86      
          
      - name: SetUp MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x86
          
      - name: Show Path
        run: echo $GITHUB_PATH
          
      - name: Make dll
        run: |
          refreshenv
          make -f MakefileAction
