name: Build TauArgusJava.dll

on:
  #push:
  # branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build TauArgusJava.dll for Windows
    #runs-on: windows-latest
    runs-on: windows-2019 #latest more often leads to install error
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SetUp Java (Zulu 8)
        uses: actions/setup-java@v3      
        with:
          distribution: 'zulu'
          java-version: '8'
          architecture: x86      
          
      - name: SetUp MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x86
          
      - name: Make dll
        run: |
          refreshenv
          c:\ProgramData\chocolatey\lib\mingw\tools\install\mingw32\bin\mingw32-make -f MakefileAction
