name: Test Environment variables

on:
  workflow_dispatch:

jobs:
  Echo:
    name: Test Environment variables
    runs-on: windows-latest
  
    steps:
      - name: SetUp mingw
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x86

      - name: Show version
        run: |
          refreshenv
          $make = Join-Path C: ProgramData chocolatey lib mingw tools install mingw32 'make --version'
          echo $make
