name: Test Environment variables

on:
  workflow_dispatch:

jobs:
  Echo:
    name: Test Environment variables
    runs-on: windows-latest
  
    steps:
      - name: SetUp mingw
        if: steps.cache-mingw.outputs.cache-hit != 'true'
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x86

      - name: Show version
        run: |
          refreshenv
          make --version
